[build]
builder = "NIXPACKS"

[variables]
NIXPACKS_PHP_ROOT_DIR = "/app/public"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.gd",
  "php82Extensions.exif",
  "nodejs_22"
]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build",
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan storage:link && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"