[build]
builder = "NIXPACKS"

[deploy]
startCommand = "php artisan storage:link && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.exif", "nodejs_22"]

[phases.build]
cmds = [
  "npm install",
  "npm run build",
  "composer install --no-dev --optimize-autoloader"
]